### ISSUE TITLE
How do I run this?

### ISSUE THREAD

**Issue by pcompassion** [evolvedlight/pydashie#14]
Is this still supported?

I did install the app, and it is missing templates static files and I get errors when I hit locahost:5000

with `python setup.py install`

IOError: [Errno 20] Not a directory: '/home/eugenekim/virtualenvs/dashing/local/lib/python2.7/site-packages/PyDashie-0.1dev-py2.7.egg/pydashie/templates/main.html'

with `python setup.py develop`

Traceback (most recent call last):
  File "/home/eugenekim/virtualenvs/dashing/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/home/eugenekim/virtualenvs/dashing/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/eugenekim/virtualenvs/dashing/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/eugenekim/virtualenvs/dashing/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/eugenekim/virtualenvs/dashing/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/eugenekim/virtualenvs/dashing/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/eugenekim/virtualenvs/dashing/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/eugenekim/virtualenvs/dashing/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/eugenekim/tmp/pydashie/pydashie/main.py", line 83, in application_css
    output = output + open(path).read()
IOError: [Errno 2] No such file or directory: 'assets/stylesheets/application.css'
Traceback (most recent call last):
  File "/home/eugenekim/virtualenvs/dashing/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/home/eugenekim/virtualenvs/dashing/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/eugenekim/virtualenvs/dashing/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/eugenekim/virtualenvs/dashing/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/eugenekim/virtualenvs/dashing/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/eugenekim/virtualenvs/dashing/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/eugenekim/virtualenvs/dashing/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/eugenekim/virtualenvs/dashing/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/eugenekim/tmp/pydashie/pydashie/main.py", line 54, in javascripts
    f = open(path)
IOError: [Errno 2] No such file or directory: 'assets/javascripts/jquery.js'

with `pip install -e git+git://github.com/evolvedlight/pydashie.git#egg=pydashie.egg`

$ pydashie
Traceback (most recent call last):
  File "/home/eugenekim/virtualenvs/dashing/bin/pydashie", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/eugenekim/virtualenvs/dashing/local/lib/python2.7/site-packages/pkg_resources.py", line 2829, in <module>
    working_set = WorkingSet._build_master()
  File "/home/eugenekim/virtualenvs/dashing/local/lib/python2.7/site-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/home/eugenekim/virtualenvs/dashing/local/lib/python2.7/site-packages/pkg_resources.py", line 742, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/eugenekim/virtualenvs/dashing/local/lib/python2.7/site-packages/pkg_resources.py", line 620, in resolve
    if dist is None or (dist not in req and replace_conflicting):
  File "/home/eugenekim/virtualenvs/dashing/local/lib/python2.7/site-packages/pkg_resources.py", line 2717, in **contains**
    item = item.parsed_version
  File "/home/eugenekim/virtualenvs/dashing/local/lib/python2.7/site-packages/pkg_resources.py", line 2321, in parsed_version
    self._parsed_version = pv = parse_version(self.version)
  File "/home/eugenekim/virtualenvs/dashing/local/lib/python2.7/site-packages/pkg_resources.py", line 2335, in version
    raise ValueError(tmpl % self.PKG_INFO, self)
ValueError: ("Missing 'Version:' header and/or PKG-INFO file", pydashie [unknown version](/home/eugenekim/virtualenvs/dashing/src/pydashie.egg))

What am I missing?

**Comment by evolvedlight** [comment]
I'm afraid this hasn't been maintained for almost three years now. You're
welcome to fix it and send a pull request, but I'm not putting time into
this currently.

**Comment by olahivepriyanka** [comment]
any updates on fixing this error ? any idea on what is missing?

**Comment by gvauter** [comment]
Ensure you move into the pydashie directory after you've cloned the repo, then run the pydashie command.   You can also launch by running main.py from within the pydashie directory.

**Comment by colbyham** [comment]
It's still broken for me. File extension error or something else related to IO
